memory:
  root_dir: ../memory
  global_memory_dir: global
  conversation_memory_dir: conversations
  index_path: memory_index.json
  max_memory_chars: 2000
  
  # 向量与图配置
  graph_path: ../memory/memory_graph.json
  embedding_model_name: BAAI/bge-small-zh-v1.5  # 轻量级小编码器
  
  # 【新增】B5 独立的本地 LLM 配置 (直接指向本地权重)
  llm_model_path: /root/siton-tmp/assignment_B/Qwen3.5-4B
  llm_tokenizer_path: /root/siton-tmp/assignment_B/Qwen3.5-4B